"""empty message

Revision ID: 9a0024cc53d2
Revises: 46cfaa7eb842
Create Date: 2018-10-17 15:39:48.138028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0024cc53d2'
down_revision = '46cfaa7eb842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'state')
    # ### end Alembic commands ###
