# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180925_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
