# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_isdelete',
        ),
    ]
